blog/urls.py
from django.urls import path
from django.shortcuts import redirect
from . import views

app_name = 'blog'

urlpatterns = [

    path('', views.home, name='home'),
]

blogproject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register'),
    path('profile/', views.profile_view, name='profile')
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    content = models.TextField(max_length=5000)

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from django.conf import settings

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default=settings.DEFAULT_PROFILE_IMG, upload_to='prof_images')
    
    def __str__(self):
        return f"{self.user.username}'s profile"

    def save(self, *args, **kwargs):
        super().save( *args, **kwargs)

        img = Image.open(self.image.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model=Profile
        fields = ['image']

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(required=False)

    class Meta:
        model=User
        fields = ['username', 'email', 'password1', 'password2']

class UserUpdateForm(forms.ModelForm):

    email = forms.EmailField(required=False)
    username = forms.CharField()

    class Meta:
        model=User
        fields = ['username', 'email']

blog/views.py
from django.shortcuts import render

def home(request):
    return render(request,'blog/home.html')

users/views.py
from django.shortcuts import render,redirect
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth import login,logout, authenticate
from django.contrib.auth.views import LoginView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.forms import AuthenticationForm

from .forms import ProfileUpdateForm,UserRegisterForm, UserUpdateForm
from .models import Profile

def login_view(request):
    if request.user.is_authenticated:
        messages.add_message(request, messages.WARNING,f'You are already logged in as "{request.user.username}"')
        return redirect(reverse('blog:home'))
    else:
        if request.method == 'POST':
            form = AuthenticationForm(data=request.POST)
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                messages.add_message(request,messages.SUCCESS,f'Welcome back {user.username}.')
                login(request,user)
                return redirect(reverse('blog:home'))
        else:
            form = AuthenticationForm()    

    return render(request, 'users/login.html', {'form':form})

def logout_view(request):
    if request.user.is_authenticated:
        logout(request)
        messages.add_message(request, messages.INFO,f'Logout successful.')
    else:
        messages.add_message(request, messages.INFO,f'You are not logged in.')
    return redirect(reverse('blog:home'))

def register_view(request):
    if request.user.is_authenticated:
        messages.add_message(request, messages.WARNING,f"You can't register a new user while logged in")
        return redirect(reverse('blog:home'))
    if request.method == "POST":
        form = UserRegisterForm(data=request.POST)
        if form.is_valid():
            form.save()
            username = request.POST['username']
            messages.add_message(request, messages.INFO,f"Welcome {username}! You can now Log In with your new account.")
            return redirect(reverse('users:login'))
        
    else:
        form = UserRegisterForm()
    
    return render(request,'users/register.html',{'form':form})

def profile_view(request):
    if not request.user.is_authenticated:
        messages.add_message(request, messages.INFO,f'You need to log in to access your profile.')
        return redirect(reverse('users:login'))

    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.add_message(request, messages.SUCCESS,f"Profile succesfully updated.")
            return redirect(reverse('users:profile'))

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)
        
        context = {'u_form':u_form,'p_form':p_form}


    return render(request,'users/profile.html', context)

blog/templates/blog/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>Blog app</title>
  </head>
  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <div class="container container-fluid">
      {%block navbar%}
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{%url 'blog:home'%}">Home</a>
              </li>
            </ul>
            <ul class="navbar-nav mb-2 mb-lg-0">
              {%if user.is_authenticated%}
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{%url 'users:profile'%}">Profile</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{%url 'users:logout'%}">Logout</a>
                </li>
              {%else%}
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{%url 'users:register'%}">Register</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{%url 'users:login'%}">Login</a>
                </li>
              {%endif%}
            </ul>
          </div>
        </div>
      </nav>
      {%endblock navbar%}
      {%if messages%}
        {%for msg in messages%}
          <div class="alert alert-{{msg.tags}} alert-dismissible fade show" role="alert">
            {{msg}}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        {%endfor%}
      {%endif%}
      {%block content%}
      {%endblock content%}
    </div>
  </body>
</html>

blog/templates/blog/home.html
{%extends 'blog/base.html'%}
{%block content%}
<p>Home</p>
{%endblock content%}

users/templates/users/login.html
{%extends 'blog/base.html'%}
{%load crispy_forms_tags%}
{%block content%}
<form action="{%url 'users:login'%}" method="post">
  {%csrf_token%}
  {{form|crispy}}
 
  <input class="btn btn-primary" type="submit" value="Login">
</form>
{%endblock content%}

users/templates/users/logout.html
{%extends 'blog/base.html'%}
{%block content%}
<h1>Logout</h1>
{%endblock content%}

users/templates/users/profile.html
{%extends 'blog/base.html'%}
{%load crispy_forms_tags%}
{%block content%}
<h2>la profile de {{user.username}}</h2>
<form method="post" enctype="multipart/form-data">
  <fieldset class="form-group">
  {%csrf_token%}
  {{u_form|crispy}}
  {{p_form|crispy}}
  </fieldset>
  <div class="form-group">
    <input class="btn btn-primary" type="submit" value="Update">
  </div>
</form>
{%endblock content%}

users/templates/users/register.html
{%extends 'blog/base.html'%}
{%load crispy_forms_tags%}
{%block content%}
<form action="{%url 'users:register'%}" method="post">
  {%csrf_token%}
  {{form|crispy}}
 
  <input class="btn btn-primary" type="submit" value="Register">
</form>
{%endblock content%}